### PR TITLE
Racket ->  🏸

### PR DESCRIPTION
**Pull request by florence**
Because

### CODE REVIEW

**Comment by AlexKnauth** [comment]
This should be in a separate package. I'm working on another package now, for `#lang gnal λ`

**Comment by florence** [comment]
Unfortunately you can't name a package 🏸 :(

**Comment by AlexKnauth** [comment]
You can name a collection that though

**Comment by AlexKnauth** [comment]
I guess I'll have to name my packgae `gnal-lambda` or something then

**Pull request closed without merging**
